export { closures } from "./closures";
export { promises } from "./promises";
export { async } from "./asyncawait";
export { eventloop } from "./eventloop";
export { hoisting } from "./hoisting";
export { prototypes } from "./prototypes";
export { eventdelegation } from "./eventdelegation";
export { debouncing } from "./debouncing";
export { Throttling } from "./throttling";
